<?php
/**
 * AMPass — Version Information
 * 
 * This file is auto-generated by scripts/sync-version.php
 * Source: GitHub commit count on main branch.
 * Display format: V1.{commit_count}
 * Semver format: 1.{commit_count}.0
 * 
 * Do NOT edit manually — run: php scripts/sync-version.php
 */

define('AMPASS_VERSION_MAJOR', 1);
define('AMPASS_COMMIT_COUNT', 63);
define('AMPASS_VERSION_DISPLAY', 'V1.63');
define('AMPASS_VERSION_SEMVER', '1.63.0');
define('AMPASS_COMMIT_SHA', '144bdbcabb54b9176dbaeec2ba5d5802c7dfa7bc');
define('AMPASS_VERSION_UPDATED_AT', '2026-05-20T12:32:27+02:00');

// Map to legacy APP_VERSION constant if not already defined
if (!defined('APP_VERSION')) {
    define('APP_VERSION', AMPASS_VERSION_SEMVER);
}
if (!defined('APP_VERSION_DISPLAY')) {
    define('APP_VERSION_DISPLAY', AMPASS_VERSION_DISPLAY);
}
