<?php
/**
 * AMPass — Version Sync Script (CLI only)
 * 
 * Detects GitHub commit count and updates all version files.
 * Run before building desktop app or browser extension.
 * 
 * Usage:
 *   php scripts/sync-version.php
 * 
 * Environment variables:
 *   GITHUB_TOKEN — optional, for higher API rate limits
 *   AMPASS_REPO_OWNER — default: pranto48
 *   AMPASS_REPO_NAME — default: ampass-secure-vault
 *   AMPASS_BRANCH — default: main
 * 
 * SECURITY: This script is CLI-only. Never expose on web.
 */

if (php_sapi_name() !== 'cli') {
    http_response_code(403);
    die('CLI only');
}

$owner = getenv('AMPASS_REPO_OWNER') ?: 'pranto48';
$repo = getenv('AMPASS_REPO_NAME') ?: 'ampass-secure-vault';
$branch = getenv('AMPASS_BRANCH') ?: 'main';
$token = getenv('GITHUB_TOKEN') ?: '';

$rootDir = realpath(__DIR__ . '/..');
if (!$rootDir) {
    fwrite(STDERR, "ERROR: Cannot determine project root\n");
    exit(1);
}

echo "AMPass Version Sync\n";
echo "Repository: {$owner}/{$repo} (branch: {$branch})\n";
echo "Project root: {$rootDir}\n\n";

// ============================================================
// DETECT COMMIT COUNT AND SHA
// ============================================================

$commitCount = 0;
$commitSha = '';

// Method A: Local .git directory
$gitDir = $rootDir . '/.git';
if (is_dir($gitDir)) {
    echo "Detecting version from local .git...\n";
    $count = trim(shell_exec('git -C ' . escapeshellarg($rootDir) . ' rev-list --count HEAD 2>/dev/null') ?? '');
    $sha = trim(shell_exec('git -C ' . escapeshellarg($rootDir) . ' rev-parse HEAD 2>/dev/null') ?? '');
    
    if (is_numeric($count) && (int)$count > 0) {
        $commitCount = (int)$count;
        $commitSha = $sha;
        echo "  Local git: {$commitCount} commits, SHA: " . substr($commitSha, 0, 8) . "\n";
    }
}

// Method B: GitHub API (if local git failed or not available)
if ($commitCount === 0) {
    echo "Detecting version from GitHub API...\n";
    $result = githubGetCommitCount($owner, $repo, $branch, $token);
    if ($result) {
        $commitCount = $result['count'];
        $commitSha = $result['sha'];
        echo "  GitHub API: {$commitCount} commits, SHA: " . substr($commitSha, 0, 8) . "\n";
    } else {
        fwrite(STDERR, "WARNING: Could not detect commit count. Keeping existing version.\n");
        exit(0);
    }
}

if ($commitCount === 0) {
    fwrite(STDERR, "ERROR: Commit count is 0. Cannot update version.\n");
    exit(1);
}

// ============================================================
// COMPUTE VERSION STRINGS
// ============================================================

$major = 1;
$display = "V{$major}.{$commitCount}";
$semver = "{$major}.{$commitCount}.0";
$updatedAt = date('c');

echo "\nVersion: {$display} ({$semver})\n";
echo "Commit: " . substr($commitSha, 0, 8) . "\n";
echo "Updated: {$updatedAt}\n\n";

// ============================================================
// UPDATE FILES
// ============================================================

$updated = 0;

// 1. ampass/app/version.php
$versionPhp = <<<PHP
<?php
/**
 * AMPass — Version Information
 * 
 * This file is auto-generated by scripts/sync-version.php
 * Source: GitHub commit count on main branch.
 * Display format: V1.{commit_count}
 * Semver format: 1.{commit_count}.0
 * 
 * Do NOT edit manually — run: php scripts/sync-version.php
 */

define('AMPASS_VERSION_MAJOR', {$major});
define('AMPASS_COMMIT_COUNT', {$commitCount});
define('AMPASS_VERSION_DISPLAY', '{$display}');
define('AMPASS_VERSION_SEMVER', '{$semver}');
define('AMPASS_COMMIT_SHA', '{$commitSha}');
define('AMPASS_VERSION_UPDATED_AT', '{$updatedAt}');

// Map to legacy APP_VERSION constant if not already defined
if (!defined('APP_VERSION')) {
    define('APP_VERSION', AMPASS_VERSION_SEMVER);
}
if (!defined('APP_VERSION_DISPLAY')) {
    define('APP_VERSION_DISPLAY', AMPASS_VERSION_DISPLAY);
}

PHP;

$versionPath = $rootDir . '/ampass/app/version.php';
if (file_put_contents($versionPath, $versionPhp) !== false) {
    echo "  Updated: ampass/app/version.php\n";
    $updated++;
}

// 2. Browser extension manifest.json
$manifestPath = $rootDir . '/clients/browser-extension/manifest.json';
if (file_exists($manifestPath)) {
    $manifest = json_decode(file_get_contents($manifestPath), true);
    if ($manifest) {
        $manifest['version'] = $semver;
        $manifest['version_name'] = $display;
        $json = json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
        file_put_contents($manifestPath, $json);
        echo "  Updated: clients/browser-extension/manifest.json\n";
        $updated++;
    }
}

// 3. Desktop tauri.conf.json
$tauriConfPath = $rootDir . '/clients/desktop-tauri/src-tauri/tauri.conf.json';
if (file_exists($tauriConfPath)) {
    $tauriConf = json_decode(file_get_contents($tauriConfPath), true);
    if ($tauriConf) {
        $tauriConf['version'] = $semver;
        $json = json_encode($tauriConf, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
        file_put_contents($tauriConfPath, $json);
        echo "  Updated: clients/desktop-tauri/src-tauri/tauri.conf.json\n";
        $updated++;
    }
}

// 4. Desktop Cargo.toml
$cargoPath = $rootDir . '/clients/desktop-tauri/src-tauri/Cargo.toml';
if (file_exists($cargoPath)) {
    $cargo = file_get_contents($cargoPath);
    $cargo = preg_replace('/^version\s*=\s*"[^"]*"/m', 'version = "' . $semver . '"', $cargo, 1);
    file_put_contents($cargoPath, $cargo);
    echo "  Updated: clients/desktop-tauri/src-tauri/Cargo.toml\n";
    $updated++;
}

// 5. docs/version.json
$docsDir = $rootDir . '/ampass/docs';
if (!is_dir($docsDir)) @mkdir($docsDir, 0755, true);
$versionJson = json_encode([
    'display' => $display,
    'semver' => $semver,
    'commit_count' => $commitCount,
    'commit_sha' => $commitSha,
    'updated_at' => $updatedAt
], JSON_PRETTY_PRINT) . "\n";
file_put_contents($docsDir . '/version.json', $versionJson);
echo "  Updated: ampass/docs/version.json\n";
$updated++;

echo "\nDone! Updated {$updated} files.\n";
echo "Version: {$display} ({$semver})\n";

// ============================================================
// HELPER FUNCTIONS
// ============================================================

/**
 * Get commit count from GitHub API.
 * Uses the Link header pagination trick: request page 1 with per_page=1,
 * then parse the last page number from the Link header.
 */
function githubGetCommitCount(string $owner, string $repo, string $branch, string $token): ?array {
    $url = "https://api.github.com/repos/{$owner}/{$repo}/commits?sha={$branch}&per_page=1";
    $headers = ['User-Agent: AMPass-VersionSync/1.0', 'Accept: application/vnd.github.v3+json'];
    if ($token) $headers[] = "Authorization: token {$token}";

    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_TIMEOUT => 15,
        CURLOPT_HEADER => true
    ]);
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $headerSize = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    curl_close($ch);

    if ($httpCode !== 200) {
        fwrite(STDERR, "  GitHub API returned HTTP {$httpCode}\n");
        return null;
    }

    $headerStr = substr($response, 0, $headerSize);
    $body = substr($response, $headerSize);

    // Parse commit SHA from response body
    $commits = json_decode($body, true);
    $sha = $commits[0]['sha'] ?? '';

    // Parse commit count from Link header
    $count = 1; // At least 1 commit if we got here
    if (preg_match('/page=(\d+)>;\s*rel="last"/', $headerStr, $matches)) {
        $count = (int)$matches[1];
    }

    return ['count' => $count, 'sha' => $sha];
}
